### ISSUE TITLE
Using while(true)

### ISSUE THREAD

**Issue by nalauder** [NexusTarget/Bleep-Bloop#1]
in the testLineFollow.cpp code, a while(true) statement has been used. Because of this, the code will not be able to move off the line section to the maze section. We need to unsure that the code knows the robot knows the difference between leaving the line follow part and just losing sight of the line

**Comment by NexusTarget-zz** [comment]
for now this is by design as i havent made any attempts on the sensor code. I am still fiddling with the PID controller. that is why it is in a constant while loop. i have code written to implement a break to determine when to switch the code over to the sensor but for now it is redundant.

**Comment by nalauder** [comment]
Sweet as, i mainly put this as a documentation thing for our final report, identifying problems and solutions etc

**Comment by krishnaKapadia** [comment]
Keep the while loop true until such time that the IR sensor detects something, cause it has to be within a certain proximity in order for it to detect. That should exit out of the while loop then continue on to the maze code without issue

**Comment by NexusTarget-zz** [comment]
we can associate a break command with the sensors so it breaks the loop!

**Comment by nalauder** [comment]
I think the break command is the way to go when the sensors start picking up objects
